version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx/site.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/log:/var/log/nginx
    networks:
      - mynetwork

  flask:
    build:
      context: python
      dockerfile: Dockerfile
    ports:
      - 1200:1200
    volumes:
      - ./python/app:/app
      - ./python/app/socket_handler.py:/app/socket_handler.py
    networks:
      - mynetwork

  mysql:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: flask
      MYSQL_USER: flask
      MYSQL_PASSWORD: flask
    volumes:
      - ./mysql/data:/var/lib/mysql
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
